export const acount = {
  username: process.env.USERNAME || '',
  password: process.env.PASSWORD || '',
};

export const tasks = [
  {
    id: '1',
    title: 'title 1',
    description: 'Description 1',
    author: 'Author 1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    title: 'title 2',
    description: 'Description 2',
    author: 'Author 2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    title: 'title 3',
    description: 'Description 3',
    author: 'Author 3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    title: 'title 4',
    description: 'Desc5iption 4',
    author: 'Author 4',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    title: 'title 5',
    description: 'Description 5',
    author: 'Author 5',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    title: 'title 6',
    description: 'Description 6',
    author: 'Author 6',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    title: 'title 7',
    description: 'Description 7',
    author: 'Author 7',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    title: 'title 8',
    description: 'Description 8',
    author: 'Author 8',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    title: 'title 9',
    description: 'Description 9',
    author: 'Author 9',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    title: 'title 10',
    description: 'Description 10',
    author: 'Author 10',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    title: 'title 11',
    description: 'Description 11',
    author: 'Author 11',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
